version: "3.9"
services:
    leaderboard_api:
        build: .
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "8000:80"
        volumes:
            - ./LeaderBoard.db:/app/LeaderBoard.db